### ISSUE TITLE
How to get a sender email id 

### ISSUE THREAD

**Issue by graphtobinary** [pimax/fb-messenger-php#10]
HI sir ,

I want to store senders email id - Fb BOT massanger  how can i get .

Thank U

**Comment by maxpinyugin** [comment]
Hi
We are can get only "first_name,last_name,profile_pic,locale,timezone,gender" - https://developers.facebook.com/docs/messenger-platform/implementation#user_profile_api

Regards

**Comment by fducom** [comment]
You can send  a submission confirm  in your app dashboard, the possibility to receive the data and add scope permission to your code UserProfile.php
