### ISSUE TITLE
default_action for MessageElement

### ISSUE THREAD

**Issue by wittfabian** [pimax/fb-messenger-php#104]
#103 

Reference: 
https://developers.facebook.com/docs/messenger-platform/send-api-reference/list-template

```
"default_action": {
     "type": "web_url",
     "url": "https://peterssendreceiveapp.ngrok.io/shop_collection",
     "messenger_extensions": true,
     "webview_height_ratio": "tall",
     "fallback_url": "https://peterssendreceiveapp.ngrok.io/"
}
```

**Comment by jason-engage** [comment]
I can probably take care of this by the end of the week if no one else does.

**Comment by nasirkhan** [comment]
`default_action` is also a part of the Generic Template and the structure is same as the List Template. 

Ref: https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template

**Comment by wittfabian** [comment]
Check the implementation of StructuredMessage.php and understand the structure.

**Comment by nasirkhan** [comment]
@jason-engage any update?

**Comment by jason-engage** [comment]
@nasirkhan I've made the pull request. Should go live soon if everything ok.

**Comment by wittfabian** [comment]
Done!

**Comment by nasirkhan** [comment]
@jason-engage I checked your pull request and found that you added a new param `default_action` in `Messages/MessageElement.php`. can you please tell me how can i use this param?

**Comment by wittfabian** [comment]
Don't use closed issues!
