### ISSUE TITLE
Persistent Menu `postback` type not working

### ISSUE THREAD

**Issue by nasirkhan** [pimax/fb-messenger-php#105]
Followed the example mentioned in the Example(https://github.com/pimax/fb-messenger-php-example). The menu was created successfully. 

The problem is the `postback` is not working, did not changed anything from the example though. The 
`web_url` and `nested` types are ok. 
When i press the button i do not receive anything from the webhook.

**Comment by wittfabian** [comment]
Do you use the index.php file as backend?

**Comment by nasirkhan** [comment]
Thanks for your response. 

Not using exactly but in a way using the index.php as backend. For the Persistent Menu i followed the example from Readme file (https://github.com/pimax/fb-messenger-php-example/blob/master/README.md)

**Comment by wittfabian** [comment]
How do you catch the postback?
index.php
```
if (!empty($message['postback'])) {
     $command = trim($message['postback']['payload']);
}
```

In this case, the bot should answer with: "Sorry. I don’t understand you."

**Comment by wittfabian** [comment]
In addition, this is the wrong repository for the issue.

**Comment by nasirkhan** [comment]
I was using http://ngrok.io on my local machine and i did not receive any response after pressing the button. but all the other responses are ok even for the Persistent Menu other response types. 

the issue is with the menu and on some other menu related issues you asked to look into the example redepositor, this is why i quoted here.

**Comment by wittfabian** [comment]
Have you tried an example with a web url?
Or do you get any error messages?

**Comment by nasirkhan** [comment]
`web_url` and `nested` type are ok and working perfectly. But i do not get any response for `postback`

**Comment by nasirkhan** [comment]
any update? did you managed to look into this?

**Comment by wittfabian** [comment]
I can't currently set the menu, and I don't know why.

**Comment by nasirkhan** [comment]
The example mentioned on the `Readme` file worked but the `index.php` did not on the example repository. which one are you using?

**Comment by wittfabian** [comment]
both

**Comment by wittfabian** [comment]
I hope I can check this tonight!

**Comment by nasirkhan** [comment]
thanks a lot

**Comment by jason-engage** [comment]
$menuItems[] = new MenuItem('postback', 'title', 'data' );
$localizedMenu[] = new LocalizedMenu('default', false, $menuItems);
$bot->setPersistentMenu($localizedMenu);

**Comment by wittfabian** [comment]
Example in https://github.com/pimax/fb-messenger-php-example/blob/master/index.php should work now.

**Comment by wittfabian** [comment]
Solved?

**Comment by nasirkhan** [comment]
thank you it is solved.
