### ISSUE TITLE
pimax\Messages\ImageMessage' not found in /app/index.php:68

### ISSUE THREAD

**Issue by HyaBlue** [pimax/fb-messenger-php#11]
hello , very nice your example , I immediately wanted to do a test ...
I mounted on heroku , but I have this problem on ImageMessage :

2016-06-01T19:11:51.946371+00:00 app[web.1]: [01-Jun-2016 19:11:51 UTC] PHP Fatal error: Uncaught Error: Class 'pimax\Messages\ImageMessage' not found in /app/index.php:68

text work fine ...

Can help me ?? tnks

**Comment by maxpinyugin** [comment]
Hello!

Please check what the ImageMessage class file included in the top of the index bot file.
I think this is the only possible problem in your case.

Regards
