### ISSUE TITLE
How shall I send Location Attachment

### ISSUE THREAD

**Issue by jiyanibharat303** [pimax/fb-messenger-php#114]
Trying to send location as attachment :
```
    $coordinates = [
        "coordinates" => [
            "lat" => "20.464079",
            "long" =>  "74.996857"
        ]
    ];
    
  $bot->send(
    new StructuredMessage($senderID,
      StructuredMessage::TYPE_GENERIC,
      [
          'text' => 'Location',
      ],
      [ 
            new Attachment(Attachment::TYPE_LOCATION, $coordinates,[]) 
      ]
    ));
```

Please help

**Comment by wittfabian** [comment]
Use markdown in your description

**Comment by wittfabian** [comment]
Check the examples for `StructuredMessage `:
https://github.com/pimax/fb-messenger-php-example

**Comment by jiyanibharat303** [comment]
Hello Sir,
I have tried those that is working with the button elements but not with attachments. Can you show and example for attachments.

**Comment by wittfabian** [comment]
Your example does not match with the one we created!

**StructuredMessage**
```
__construct($recipient, $type, $data, $quick_replies = array(), $tag = null, $notification_type = parent::NOTIFY_REGULAR)
```

I think locations as attachments is not possible.
https://developers.facebook.com/docs/messenger-platform/send-api-reference/contenttypes

**Comment by wittfabian** [comment]
Check this workaround:
https://stackoverflow.com/questions/38017382/how-to-send-location-from-facebook-messenger-platform

**Comment by wittfabian** [comment]
solved?

**Comment by wittfabian** [comment]
No answer, closed!
