### ISSUE TITLE
How to differentiate the text inputs in messages

### ISSUE THREAD

**Issue by jiyanibharat303** [pimax/fb-messenger-php#116]
Hello Please help -
I have implemented the Pimax Library for Bot its working cool -
BOT - Please enter email address
User - types email address

BOT - Please enter address
User - types address

In these cases I will only get the inputs from them in messages type text - so shall I like run an verification of address and email address every time I receive a message or is there a solution to it.

**Comment by wittfabian** [comment]
Your question is how to verify the email address and the personal address?

**Comment by wittfabian** [comment]
For the E-Mail you can use `filter_var()` 
http://php.net/manual/de/filter.examples.validation.php

Or you can send a link to an external page (with a form for the address etc.)

**Comment by jiyanibharat303** [comment]
No My question is - how to trace that when an question is asked then only I verify that address and email address. Because each message will come under $command = $message['message']['text']; So do I check every time whether email or address and proceed.

**Comment by wittfabian** [comment]
I would set a flag in the database, that marks each step of the conversation.

**Comment by wittfabian** [comment]
solved?

**Comment by jiyanibharat303** [comment]
Yes m maintaining flags as you suggested Thank you :+1:  you can close the ticket
