### ISSUE TITLE
Question: How to subscribe pages with code

### ISSUE THREAD

**Issue by jiyanibharat303** [pimax/fb-messenger-php#118]
Hello,
I am using this library and its really cool. I have a section where users login with fb account and I am able to bring in there pages my question how shall I subscribe those pages with my app so the bot works for those pages.
Please let know on this
Thank You

**Comment by wittfabian** [comment]
Have a look at this:
https://developers.facebook.com/docs/messenger-platform/webhook?locale=en_US

**Comment by wittfabian** [comment]
Solved?

**Comment by jiyanibharat303** [comment]
Yes Boss.
