### ISSUE TITLE
Set custom target audience.

### ISSUE THREAD

**Issue by kamal-sanjeewa** [pimax/fb-messenger-php#120]
in fb documentation 

"target_audience":{
  "audience_type":"custom",
  "countries":{
    "whitelist":["US", "CA"]
  }
}

but in set target audience function make json as 

"target_audience":{
  "audience_type":"custom",
    "whitelist":["US", "CA"]
}

**Comment by jason-engage** [comment]
Yes this should be fixed then. I will post an update later today or tomorrow, unless you want to do it first.

**Comment by kamal-sanjeewa** [comment]
Can I contribute for this repo?

**Comment by jason-engage** [comment]
I think that's fine, just do a pull request with the changes.
