### ISSUE TITLE
How to build Facebook Comment Auto Reply (Private Reply)

### ISSUE THREAD

**Issue by rfrkk** [pimax/fb-messenger-php#127]
I request permission for following 
manage_pages,publish_pages,read_page_mailboxes,pages_messaging,pages_messaging_subscriptions,
and want to open messenger auto reply when people comments from feed,

How to di it?

tks!

**Comment by wittfabian** [comment]
These features are not part of this SDK.
This SDK deals exclusively with the messenger.
