### ISSUE TITLE
Class 'AudioMessage' not found

### ISSUE THREAD

**Issue by Stacey940** [pimax/fb-messenger-php#129]
Hi , 

Thank you for this awesome SDK.

I am getting error when I try to send an audio message. It says Class 'AudioMessage' not found. The code I am using is : 

$bot->send(new AudioMessage($id , 'http://somewebsite.com/fb_msg/audio/contest.mp3'));

**Comment by HanafiAhmat** [comment]
At the top of your file after vendor/autoload.php, did you add this line `use pimax\Messages\AudioMessage;` ?

**Comment by Stacey940** [comment]
Oh sorry , yes, it worked. Thanks @HanafiAhmat
