### ISSUE TITLE
How can stop the bot responses when a user start to response manually?

### ISSUE THREAD

**Issue by ponghi** [pimax/fb-messenger-php#130]
Hi everyone! As I asked in the object I would like to know if and how stop the automatic bot responses once the owner of the FB page start to interact manually with the user... any suggestions?

**Comment by wittfabian** [comment]
What "bot responses" do you mean?
Can you show a example?

**Comment by ponghi** [comment]
Taking into account this example [https://github.com/pimax/fb-messenger-php-example/blob/master/index.php](https://github.com/pimax/fb-messenger-php-example/blob/master/index.php)

Try to think to this flow:
1) the user interact with the bot using the commands handled into the `switch`  with the variable `$command`
2) if he doesn't found what he looked for ask for talk with someone, for example, by clicking on a specific object `TYPE_BUTTON` with the label "Let me speak with someone..." 
3) after few minutes ME, as the owner of the FB page where is installed the bot script, write to my user "Hi, here I am, I'm Alex how can I help you?"
4) The user respond to me with "Hi Alex, I would to know _bla bla bla_" but this message will be handled by the bot script into the `switch` with the result of the `default `case **Sorry. I don’t understand you.**  


so... How can stop the bot handling of users messages if a step 3 occur?

I hope to have clarify the case...

**Comment by ponghi** [comment]
Maybe this is managed with:

>             // skip the echo of my own messages
>             if (($message['message']['is_echo'] == "true")) {
>                 continue;
>             }

But I've tried and it doesn't work...

**Comment by wittfabian** [comment]
The messages are always delivered to the bot.
Human-to-human conversations are not provided on a bot page.

**Comment by ponghi** [comment]
...ok!
Thanks for you answers! Have a nice day

**Comment by wittfabian** [comment]
You're welcome!

**Comment by AngelosNaoumis** [comment]
https://developers.facebook.com/docs/messenger-platform/handover-protocol is there any planned implementation of handover protocol?

**Comment by wittfabian** [comment]
Pull requests are welcome
