### ISSUE TITLE
Message send not working ngrok and Laravel localhost

### ISSUE THREAD

**Issue by Yiidiir** [pimax/fb-messenger-php#136]
If you're running your WebServer in localhost just set  ``CURLOPT_SSL_VERIFYPEER`` to ``false``

or
``
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
``

it's due to an SSL certificate problem:

``
Error #:SSL certificate problem: unable to get local issuer certificate
``
Check my pull request below, it displays cURL errors if found, If this was enabled it would have saved me alot of time ~2days!

#135

**Comment by wittfabian** [comment]
#135 merged

**Comment by Yiidiir** [comment]
update #138
