### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by arsengoian** [pimax/fb-messenger-php#137]
Guys, been using your lib for a while. Still, I'd strongly prefer to use releases in production.

I can't do this with your lib because I need some new features not present in 1.0
However, it's very inconvenient because I have to composer require last known stable commit.

Last commit, for instance, introduced production-incompatible behaviour.

There hadn't been a release here until 2016 
Could you kindly make a 1.1 release?

**Comment by wittfabian** [comment]
@jason-engage
