### ISSUE TITLE
Is it possibile to hide the payload text response?

### ISSUE THREAD

**Issue by ponghi** [pimax/fb-messenger-php#140]
Hi all,

I've used a StructuredMessage with a MessageButton like this:

` new MessageButton(MessageButton::TYPE_POSTBACK, 'Info', 'def')`

**def** is my Payload and I've handled it with some generic text... but when I click on the button "Info" the bot response me with the Payload text before load the generic text...

Is it possible to hide the payload text??

![cattura](https://user-images.githubusercontent.com/36696499/37155661-187b2858-22e4-11e8-9c40-af4643802358.JPG)

**Comment by Yiidiir** [comment]
That's a weird behavior, are you skipping ``is_echo``and ``delivery`` like in the [example](https://github.com/pimax/fb-messenger-php-example/blob/master/index.php) ? Also could you show the part of your code that does the actual processing (case or whatever) ?

**Comment by ponghi** [comment]
I'm using exactly the [example](https://github.com/pimax/fb-messenger-php-example/blob/master/index.php) that you have linked.

I've also set my webhook for manage the **message_echoes** and **message_delivery** but into the variable `$message` I dont find any key like `$message['delivery']` or `$message['message']['is_echo']`

Maybe a workaround could be send an object as a payload instead of a generic text...for example:

`new MessageButton(MessageButton::TYPE_POSTBACK, 'Info', new Message($message['sender']['id'], 'This is a simple text message.'))`

Any suggestions?

**Comment by Yiidiir** [comment]
Are you sure your app subscribed in ``messages`` webhooks?
in ``https://developers.facebook.com/apps/APP_ID/webhooks/``
Are you sure you're using the admin account to test or added your account as a tester?

**Comment by ponghi** [comment]
Yes I did, bot `messages` and `message_postback`.

I'm actually using ad admin account...

**Comment by ponghi** [comment]
Everytime that I push a button, the PAYLOAD text is written to me by the bot...

**Comment by Yiidiir** [comment]
Ayy, do you mean the payload ``text`` and not the ``payload`` itself? 
You can't send payload without that text being displayed to the users, as far as i know..

**Comment by wittfabian** [comment]
@Yiidiir Yes that's right!

**Comment by Yiidiir** [comment]
maybe close this @wittfabian
