### ISSUE TITLE
Quick Replies for Phone and Email-- Need to Update Source Code

### ISSUE THREAD

**Issue by Stacey940** [pimax/fb-messenger-php#143]
Hi,

How can we implement quick replies for email and phone numbers. As this announcement shows : 
https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies#phone

Can I get an example code

**Comment by Stacey940** [comment]
I added these two constants in QuickReplyButton.php and this worked. 

    const TYPE_USER_EMAIL = "user_email";
    const TYPE_USER_PHONE = "user_phone_number";

I think it need to update the Code here , so when I update using composer update, it will not be removed

**Comment by wittfabian** [comment]
Pull Requests are welcome!

**Comment by wittfabian** [comment]
Done!

**Comment by o2-web** [comment]
было много полезных изменений, я выполнил composer install, но никакой пакет не обновился. Что я делаю неправильно? Это я к тому что хотел затянуть обновления.

**Comment by wittfabian** [comment]
We only support English.

This feature is not integrated in any version yet. If necessary, you must carry out the installation with the repo directly.

**Comment by o2-web** [comment]
sorry, upd: 
there were a lot of useful changes, I ran composer install, but no package was updated. What am I doing wrong? I mean I wanted to pool the updates.

**Comment by wittfabian** [comment]
This feature is not integrated in any version yet. If necessary, you must carry out the installation with the repo directly.
