### ISSUE TITLE
Photo url seems not visible in MessageElement

### ISSUE THREAD

**Issue by yourchoice** [pimax/fb-messenger-php#151]
Photo url seems not visible in MessageElement.

This is the url that appear in messenger:
> https://external.xx.fbcdn.net/safe_image.php?d=AQCoK7MIURiW2u4U&url=https%3A%2F%2Fd4fdb0e9.ngrok.io%2Fimgupl%2Ffeed-data%2Flg-1498216.jpg&_nc_hash=AQDOZEXUmxbfyWoY

And this is the where need to redirect, but not redirect:
https://d4fdb0e9.ngrok.io/imgupl/feed-data/lg-1498216.jpg

Maybe encoding problem !?!

Any idea?

**Comment by yourchoice** [comment]
Sorry, maybe it's the ngrok. I think this is the problem.

But question remain: any idea why not redirect ?

**Comment by jason-engage** [comment]
I have no idea, but does the domain need to be whitelisted?
-- 




*        Jason Shaw <jason@engageify.com>*, Developer
    Tel. 647 783 7463 | Skype:  jason.engage
    en.gg |  <http://en.gg/>Follow me on Facebook
<http://www.facebook.com/engagetheweb>

**Comment by yourchoice** [comment]
Yes, the proble is the ngrock.

On production working well
