### ISSUE TITLE
Regarding persistent_menu, set/update or case for the older users

### ISSUE THREAD

**Issue by yourchoice** [pimax/fb-messenger-php#154]
Regaring persistent_menu, it's normal that after : 
```
$bot->deletePersistentMenu();
$bot->setPersistentMenu(...);
```
the menu to appear just after i refresh the page ?

Another question that not depend by this lib: 

> For users that already init a chat (when no bot built), how can I set the persistent menu ?

For new users 
`$bot->setGetStartedButton('init');`
the **'init' payload**, that **set the menu** and **greeting text** working well, but for an older user if he write someting 'init' payload is sent, but PersistentMenu not appear.

**Comment by pulkit8** [comment]
"the menu to appear just after i refresh the page "

Yes, the menu will appear after you refresh the page. 


"For new users
$bot->setGetStartedButton('init');
the 'init' payload, that set the menu and greeting text working well, but for an older user if he write someting 'init' payload is sent, but PersistentMenu not appear."

Can you reframe your question please ? 
Also, the PersistentMenu can be set by you for once for all the users. I am not sure how come the init payload is affecting your persistentmenu.

P.S : Yes, the existing users who have already sent message to the page, doesn't get 'GetStarted button' until unless they clear the conversation manually.

**Comment by yourchoice** [comment]
I have a "init" paylod that is set via get started button:
`$bot->setGetStartedButton('init');`
With payload "init" i call a method "initChat" that: [set greeting text], [send a welcome message] and [set the chat menu]".

For the new users that commes in messnger after i build the bot, all is ok. They click on "Start Chat" and all things are set well... But for old messenger users, the menu seems to not appear. I checked the webhooks request and the "init" payload appear at begin, but menu not appear.

I would like to know if exists a way to set menu and for the existing users (old users) ?

I suppose, if they (old users) interact again on chat, when receive a message, i can call `$bot->setPersistentMenu(...);` , but this means to call setPersistentMenu(...), for each text writed in chat by the user. Maybe need to store a status on my server (to say if member have or not the menu set), but again not a good thing, because means a lot of checking by the my server (connections to DB).

**Comment by pulkit8** [comment]
"Start Chat" button won't appear for existing users. (In case you find a solution to this, please update me too :-D ) 
What you can do is - Whenever you receive a message, you can check if the user's FB ID exist in your database or not. If it doesn't, invoke your "initChat" function.  You can probably use redis then mysqli to fasten the process. 

PersistentMenu isn't needed to be called for every user. It's a bot window property. You need to set it once and it will be appearing for all users.

**Comment by wittfabian** [comment]
Is the problem clarified?

**Comment by wittfabian** [comment]
No Answer, closed!
If the problem persists, reopen the issue.
