### ISSUE TITLE
NON_PROMOTIONAL_SUBSCRIPTION is a tag not a type

### ISSUE THREAD

**Issue by georgecheteles** [pimax/fb-messenger-php#155]
From 1 january 2019 all messages sent outside the 24 hour window need to have the tag NON_PROMOTIONAL_SUBSCRIPTION and the messaging_type TYPE_MESSAGE_TAG.
In this library NON_PROMOTIONAL_SUBSCRIPTION is TYPE_NON_PROMOTIONAL_SUBSCRIPTION constant. That is not right. It should be a tag constant, eg TAG_NON_PROMOTIONAL_SUBSCRIPTION.
Also, the ImageMessage and VideoMessage classes do not have the tag setting.
Thanks

**Comment by georgecheteles** [comment]
Also, the ImageMessage class does not have the tag setting.

**Comment by georgecheteles** [comment]
Here is the FB documentation:
https://developers.facebook.com/docs/messenger-platform/send-messages/message-tags

**Comment by wittfabian** [comment]
Pull requests are welcome!

**Comment by wittfabian** [comment]
#156

**Comment by wittfabian** [comment]
#156

**Comment by wittfabian** [comment]
Done!
