### ISSUE TITLE
version post 2.8

### ISSUE THREAD

**Issue by gabriel-tandil** [pimax/fb-messenger-php#163]
Hello! I would like to know how to use this library for newer versions of api graph since in the FbBotApp class of this project says

```
    /** 
     * FB Messenger API Url 
     * 
     * @var string 
     */ 
    protected $apiUrl = 'https://graph.facebook.com/v2.8/';
```

and this version of the api is about to cease to be available.

Thank you
Gabriel

**Comment by ngethe** [comment]
I changed this line 


                  protected $apiUrl = 'https://graph.facebook.com/v2.8/';  out this line to 3.2 and used 



  https://developers.facebook.com/tools/api_versioning/ to upgrade my app and that seems to work.

is that all that is required to move to 3.2 ?
