### ISSUE TITLE
Chatbot doesn't work at ALL

### ISSUE THREAD

**Issue by salahy** [pimax/fb-messenger-php#165]
my chatbot used to work just fine, but it was in a demo page, when I tried to install it on live pages it didn't work, and when I tried to put it back to the demo page its also not working, the facebook changed a lot of settings recently, anything new should I consider ?

**Comment by jason-engage** [comment]
I don't think there's been any code changes here in months...

The last pull request hasn't been merged yet either...

**Comment by wittfabian** [comment]
Without any error messages or code an error analysis is difficult / not possible.

**Comment by wittfabian** [comment]
**Please use the issue template**

Would you like assistance or advice?

Issue description

Steps to reproduce

Traceback or other info

fb-messenger-php version: x.x.x / master@commit
PHP version: x.x.x

**Comment by wittfabian** [comment]
No response!

-> Close <-
