### ISSUE TITLE
Add tests and coverage via travis-ci

### ISSUE THREAD

**Issue by wittfabian** [pimax/fb-messenger-php#167]
- [x] setup Travis-CI
- [x] add .travis.yml file
- [x] add tests

* https://github.com/ankurk91/phpunit-travis-ci-coverage-example
* https://docs.travis-ci.com/user/languages/php/

**Comment by wittfabian** [comment]
@ipimax you have to add the Travis-CI App to the repo.

**Comment by maxpinyugin** [comment]
@wittfabian I have installed Travis-CI. Please, check it. Let me know if i can do anything else.

**Comment by wittfabian** [comment]
We need to activate the repo on Travis.
I don't have sufficient rights.

https://travis-ci.org/pimax/fb-messenger-php

**Comment by wittfabian** [comment]
Perfekt, works.

**Comment by maxpinyugin** [comment]
Ok. I have activated repo on Travis.
