### ISSUE TITLE
Unable to send ImageMessage (and others)

### ISSUE THREAD

**Issue by ddavidov** [pimax/fb-messenger-php#17]
See: https://github.com/pimax/fb-messenger-php/blob/master/FbBotApp.php#L46
- Now send method accepts Message objects only.
- So, how can I send for example ImageMessage if it doesn't extends Message?
  Could you please clear that restriction, or extend all xMessage classes from Message...

**Comment by ddavidov** [comment]
P.S. Happens since last pull-request (#13) merged

**Comment by dawidof** [comment]
The same issue. Have you resolved it?

**Comment by achimha** [comment]
With PR #16 it works for URLs but not with embedded images (uploaded as part of the transaction).

**Comment by dawidof** [comment]
Thanks

Made
`composer require pimax/fb-messenger-php`
`composer update`

And everything works))

**Comment by fducom** [comment]
Hi there

Fixed
my pull request ->
https://github.com/pimax/fb-messenger-php/pull/24/commits/0755776465bd730870a45d861f0ee9c950edb1cb

**Comment by maxpinyugin** [comment]
fixed
