### ISSUE TITLE
Update minimum PHP version

### ISSUE THREAD

**Issue by wittfabian** [pimax/fb-messenger-php#172]
We should update the minimum PHP version to 7.X.X

**Comment by jason-engage** [comment]
I'm running it on a php 7 server with no issues.

**Comment by wittfabian** [comment]
The new tests are also based on php 7

**Comment by wittfabian** [comment]
https://www.php.net/supported-versions.php

**Comment by jason-engage** [comment]
This is great, we can start using the ?? Operator (Null Coalesce Operator)

Best operator ever.

**Comment by wittfabian** [comment]
We should switch to v7.1 with the new tests

**Comment by jason-engage** [comment]
What about users running on PHP 5? Will you go up a major version? Isn't it set to dev-master in composer? That's always confused me, but I'm not so advanced with composer to begin with.

**Comment by wittfabian** [comment]
PHP <= 7: 
"A release that is no longer supported. Users of this release should upgrade as soon as possible, as they may be exposed to unpatched security vulnerabilities. "

major version: yes
dev-master composer confuses me too

I will look at the composer settings

**Comment by wittfabian** [comment]
https://getcomposer.org/doc/articles/aliases.md#branch-alias
