### ISSUE TITLE
audio, video, file

### ISSUE THREAD

**Issue by dawidof** [pimax/fb-messenger-php#19]
Could you please add functionality to send audio, video and file type to fb?

**Comment by vhcsilva** [comment]
dawidof, i created a new php file called AudioMessage.php with the code of ImageMessage.php, then i changed the 'type' on line 55 and 68 to 'audio'. It worked to me.

**Comment by dawidof** [comment]
Are you able to upload files from your computer?

**Comment by vhcsilva** [comment]
I'm uploading files to my website. I did not try upload direct to Messenger Plataform.

**Comment by wittfabian** [comment]
video, audio, image, and file messages are implemented
