### ISSUE TITLE
unable to upload image from local computer

### ISSUE THREAD

**Issue by dawidof** [pimax/fb-messenger-php#20]
Sending image using url works ok. But while uploading image from local computer, receive an error `{"error":{"message":"(#100) The parameter message[attachment][payload] is required","type":"OAuthException","code":100,"fbtrace_id":"FFaO+JohtCZ"}}`

**Comment by informeronline** [comment]
I have the same problem.

```
[error] => Array
    (
        [message] => (#100) The parameter message[attachment][payload] is required
        [type] => OAuthException
        [code] => 100
        [fbtrace_id] => FQjLSkpQD0j
    )
```

Update:

After a composer update i got:

```
[error] => Array
    (
        [message] => (#100) Failed to fetch the file from the url
        [type] => OAuthException
        [code] => 100
        [fbtrace_id] => BRrxKxIZ90S
    )
```

I'am 100% sure the path to the local file is ok.

**Comment by kapilkd13** [comment]
hi I have tracked the reason behind it. have a look at http://stackoverflow.com/questions/39375577/how-to-urlencode-a-empty-arraynot-null-but-empty-in-php-to-pass-to-curlopt-po

**Comment by wittfabian** [comment]
#81

**Comment by wittfabian** [comment]
solved?

**Comment by wittfabian** [comment]
Closed - no feedback!
