### ISSUE TITLE
How to get the current geo location of the logined user in messenger chat bot

### ISSUE THREAD

**Issue by rekhacarillom** [pimax/fb-messenger-php#23]
Hello,

How to get the current geo location of the logined user in messenger chat bot?

**Comment by rekhacarillom** [comment]
Please help me.Its very urgent..I want to get the current location of a messenger chat bot user,who is using the chat bot currenlty and i want to display some details according to that location

**Comment by fducom** [comment]
Hello
It is necessary to get permission from the support on the right
App Review for Messenger

**Comment by rekhacarillom** [comment]
Okay .Thank you for the reply
