### ISSUE TITLE
'Get Started' button is not showing

### ISSUE THREAD

**Issue by rekhacarillom** [pimax/fb-messenger-php#29]
Hello,
The 'Get started ' button is not showing when a user first start to chat with the bot.Can anyone find out the issue....

**Comment by samtsai15** [comment]
use Curl Post
https://developers.facebook.com/docs/messenger-platform/thread-settings/get-started-button

> The Get Started button is only rendered the first time the user interacts with a the Page on Messenger.

So you need to "Delete conversation" and try again.

**Comment by wittfabian** [comment]
Should work now

**Comment by howardlai** [comment]
Already "Delete conversation" and try again, but failed.

it turns out that developer need to add "Tester" roles for such user, and user will see the "Get Started" button. Is it a Facebook Bug??
