### ISSUE TITLE
Problem with structured message

### ISSUE THREAD

**Issue by samuburgueno** [pimax/fb-messenger-php#3]
Hi, thanks for this implementation to facebook bot. I try the example and the structured message is not working for me. Work for you?
Thanks!

**Comment by maxpinyugin** [comment]
Hi!
Please, write your code here.
Thanks

**Comment by samuburgueno** [comment]
The code is your example, $command contain "All jobs", that's user's message, the bot is not returning anything. 

**PHP CODE**

`switch ($command)
                {
                    case 'All jobs':
                        // Send Structured message
                        $bot->send(new StructuredMessage($message['sender']['id'],
                            StructuredMessage::TYPE_BUTTON,
                            [
                                'title' => 'Choose category',
                                'buttons' => [
                                    new MessageButton(MessageButton::TYPE_POSTBACK, 'All jobs'),
                                    new MessageButton(MessageButton::TYPE_POSTBACK, 'Web Development'),
                                    new MessageButton(MessageButton::TYPE_POSTBACK, 'Software Development & IT')
                                ]
                            ]
                        ));
                    break;
                }`

**APACHE LOG**

`2016-04-14T19:25:38.540099+00:00 heroku[router]: 
at=info method=POST path="/" host=iebcentro-bot.herokuapp.com request_id=fb010846-5872-4c5a-bbf8-ab713e93a53e fwd="66.220.158.119" dyno=web.1 connect=2ms service=133ms status=200 bytes=150

2016-04-14T19:26:09.278245+00:00 app[web.1]: [14-Apr-2016 19:26:09 UTC] PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

2016-04-14T19:26:09.395358+00:00 app[web.1]: 10.146.27.104 - - [14/Apr/2016:19:26:09 +0000] "POST / HTTP/1.1" 200 - "-" "-`

**Comment by matthijsotterloo** [comment]
Having the same issue. I'm getting this in my log: [Thu Apr 14 21:46:56.791311 2016] [:error] [pid 21798] [client 173.252.90.109:47076] PHP Notice:  Undefined index: text in /home/matthijs/www/matthijsotterloo.com/facebook/Messages/StructuredMessage.p

**Comment by maxpinyugin** [comment]
Right. 
It's my mistake in example.
Please try change 'title' index to 'text'
Like this :
`$bot->send(new StructuredMessage($message['sender']['id'],
                      StructuredMessage::TYPE_BUTTON,
                      [
                          'text' => 'Choose category',
                          'buttons' => [
                              new MessageButton(MessageButton::TYPE_POSTBACK, 'First button'),
                              new MessageButton(MessageButton::TYPE_POSTBACK, 'Second button'),
                              new MessageButton(MessageButton::TYPE_POSTBACK, 'Third button')
                          ]
                      ]
                  ));`

**Comment by samuburgueno** [comment]
Yes! That works, thanks again! 💃

**Comment by MartinTerp** [comment]
on the same subject, can you post an example on the TYPE_GENERIC ?

```
                        case 'some jobs':
                            // Send Structured message
                            $bot->send(new StructuredMessage($message['sender']['id'],
                            StructuredMessage::TYPE_GENERIC,
                            [
                            'text' => 'Choose category',
                            'buttons' => [
                                new MessageButton(MessageButton::TYPE_POSTBACK, 'All jobs'),
                                new MessageButton(MessageButton::TYPE_POSTBACK, 'Web Development'),
                                new MessageButton(MessageButton::TYPE_POSTBACK, 'Software Development & IT')
                            ],
                            'image_url' => 'http://petersapparel.parseapp.com/img/item100-thumb.png',
                            'subtitle' => 'its nice',
                            ]
                            ));
                            break;
```

when i use this, its responds with nothing in the message box

**Comment by maxpinyugin** [comment]
I make new repo for advanced examples.
Please, see https://github.com/pimax/fb-messenger-php-example

**Comment by graphtobinary** [comment]
HI How can we Get and use multiple input from users in single case For example 
BOT :- What is your name 
User :- Prashant
BOT:- What is your Age.
Users :- 16
Execute the entire section 
BOT :-- Nothing Found In your age Mr. Prashant.

@ipimax Love your code Thanks for Sharing Please Help me

**Comment by maxpinyugin** [comment]
Hello @prashant052

For the future please open new issue, not a reopen resolved, because this question actual only for you, not for all issue participants.

About your question:
This logic not implemented in the SDK because this is App logic.
For implement this, you need to save received answers locally on your  server (where bot installed).
It's maybe database, nosql or just files.
In your case, when client sent answer on first question, we need save answer and current step index for db/file. You can identify session based on $message['sender']['id'].

Regards
