### ISSUE TITLE
How to make quick replies ?

### ISSUE THREAD

**Issue by edinsof** [pimax/fb-messenger-php#32]
Hi how to make quick replies?

**Comment by WhiteSaxo** [comment]
Just do something like that:
`$quick_replies = [
                                        [
                                            "content_type" => "text",
                                            "title" => "title",
                                            "payload" => "payload"
                                        ],
                                        [
                                            "content_type" => "text",
                                            "title" => "title",
                                            "payload" => "payload"
                                        ]
                                    ];`
and than create a quick reply:
`new QuickReply($message['sender']['id'], 'text', $quick_replies)`

**Comment by wittfabian** [comment]
Quick replies are supported with the current implementation!
