### ISSUE TITLE
How to open a webview using messenger extensions

### ISSUE THREAD

**Issue by akshaygupta1996** [pimax/fb-messenger-php#35]

**Comment by ghassen1988** [comment]
Did you manage to do it ? I need a webview in my use case

**Comment by akshaygupta1996** [comment]
No not yet...i did a other way round.i used flight template instead.

**Comment by ghassen1988** [comment]
Oh ... that is not what I am looking for but good for you if it worked . My use case is a payment webview so it need to be configured from scratch

**Comment by wittfabian** [comment]
#52

**Comment by ghassen1988** [comment]
is there an example how to do it ?

**Comment by wittfabian** [comment]
Closed - duplicate of #52
