### ISSUE TITLE
How to use  a messenger  plugin  on  my  website???

### ISSUE THREAD

**Issue by qwe356558603** [pimax/fb-messenger-php#39]
![image](https://cloud.githubusercontent.com/assets/18321666/19431735/3f6ba952-948c-11e6-8e4b-b73a5f374a04.png)

**Comment by qwe356558603** [comment]
![image](https://cloud.githubusercontent.com/assets/18321666/19431735/3f6ba952-948c-11e6-8e4b-b73a5f374a04.png)

**Comment by wittfabian** [comment]
can you show me the link?

**Comment by wittfabian** [comment]
Take a look at the links:
https://developers.facebook.com/docs/messenger-platform/referral-params

https://developers.facebook.com/docs/messenger-platform/plugin-reference/message-us

**Comment by wittfabian** [comment]
Solved?

**Comment by wittfabian** [comment]
No Answer. Closed!
