### ISSUE TITLE
add possibility to send QuickReply together with StructuredMessage

### ISSUE THREAD

**Issue by russ666** [pimax/fb-messenger-php#45]
it's allowed by API but does't implemented in client

**Comment by wittfabian** [comment]
Is there an example in the docs?

**Comment by russ666** [comment]
[Quick Replies API Docs](https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies)
it just needs to append `quick_replies` array to any message

**Comment by wittfabian** [comment]
Thx

**Comment by wittfabian** [comment]
Done

**Comment by wittfabian** [comment]
#79
