### ISSUE TITLE
implement list template

### ISSUE THREAD

**Issue by russ666** [pimax/fb-messenger-php#46]
there are new feature in messenger api
[list-template](https://developers.facebook.com/docs/messenger-platform/send-api-reference/list-template)

**Comment by wittfabian** [comment]
#61

**Comment by ngethe** [comment]
Help with Example useage on list I tried this 

               case 'g':
                    $bot->send(new StructuredMessage($message['sender']['id'],
                        StructuredMessage::TYPE_LIST,
                        [
                            'elements' => [
                                new MessageElement("top_element_style", "large", "image_url","https://www.hello.com/img_/hello_logo_hero.png" , [
                                    new MessageButton(MessageButton::TYPE_POSTBACK, 'First button'),
                                    new MessageButton(MessageButton::TYPE_WEB, 'Web link', 'http://facebook.com')
                                ]),
                                new MessageElement("Second item", "Item description", "",  "image_url","https://www.hello.com/img_/hello_logo_hero.png",  [
                                    new MessageButton(MessageButton::TYPE_POSTBACK, 'First button'),
                                    new MessageButton(MessageButton::TYPE_POSTBACK, 'Second button')
                                ]),
                                new MessageElement("Third item", "Item description", "", [
                                    new MessageButton(MessageButton::TYPE_POSTBACK, 'First button'),
                                    new MessageButton(MessageButton::TYPE_POSTBACK, 'Second button')
                                ])
                            ]
                        ]
                    ));

                break;


But NOT working

**Comment by wittfabian** [comment]
Don't use this issue for your problems.

**Comment by ngethe** [comment]
OK @wittfabian but please help with example to implement list..
