### ISSUE TITLE
Add Payload

### ISSUE THREAD

**Issue by drosanda** [pimax/fb-messenger-php#50]
Hi All,

how to add payload to a button?

**Comment by wittfabian** [comment]
This is not supported with this implementation!

Have a look at this:
https://github.com/wittfabian/fb-messenger-php/blob/master/Messages/MessageButton.php

**Comment by wittfabian** [comment]
Maybe you can add a pull request

**Comment by ghassen1988** [comment]
How to add payload to a button inside a structured message ? is it not supported ? 
Then why making an SDK if it does not support a basic functionality like this 
There are bugs also in the SDK I think you should reconsider before making an SDK again pimax

**Comment by wittfabian** [comment]
What is your problem?
Open an issue if you know something about a bug.

**Comment by wittfabian** [comment]
I work on this implementation!

**Comment by wittfabian** [comment]
Do you mean something like this: 

https://developers.facebook.com/docs/messenger-platform/send-api-reference/share-button

Have a look at this:
https://github.com/pimax/fb-messenger-php/blob/master/Messages/StructuredMessage.php

**Comment by drosanda** [comment]
Yes like that, thanks :)
