### ISSUE TITLE
Class 'pimax\Messages\Attachment' not found 

### ISSUE THREAD

**Issue by tuanxuong** [pimax/fb-messenger-php#51]
Hello Sir,
when i type "image" to send one photo from url to User, i see a issues with log

> [15-Jan-2017 12:31:33 Asia/Ho_Chi_Minh] PHP Fatal error:  Class 'pimax\Messages\Attachment' not found in /home/xxxx/public_html/xxxxxxx/Messages/ImageMessage.php on line 49

how to fix it. please

**Comment by wittfabian** [comment]
Maybe the include is missing?

`use pimax\Messages\Attachment`

**Comment by tuanxuong** [comment]
when i include

> include 'Messages/Attachment.php';
> use pimax\Messages\Attachment;
> 

Log error: 
[15-Jan-2017 22:20:29 Asia/Ho_Chi_Minh] PHP Fatal error:  Call to undefined function pimax\Messages\mime_content_type() in /home/xxxx/public_html/xxxx/Messages/ImageMessage.php on line 56

**Comment by tuanxuong** [comment]
Yes.
I chang mime_content_type to finfo_file
i work
Tks wittfabian

**Comment by wittfabian** [comment]
Thanks for the hint.
