### ISSUE TITLE
Webview not supported ?

### ISSUE THREAD

**Issue by ghassen1988** [pimax/fb-messenger-php#52]
I am trying to open a webview using this sdk , but it does not work . Are you planning on implementing this feature ?

**Comment by wittfabian** [comment]
Yes

**Comment by ghassen1988** [comment]
is there an example how to do it ?

**Comment by wittfabian** [comment]
Webview is currently not supported, but I work on it.

**Comment by ghassen1988** [comment]
Ok looking forward to it thank you

**Comment by wittfabian** [comment]
#56

**Comment by wittfabian** [comment]
done
