### ISSUE TITLE
Laravel 5.3 instructions anyone?

### ISSUE THREAD

**Issue by seatechdev** [pimax/fb-messenger-php#53]
I am looking for the guidance on the following:

1.  what paths to user for Providers and Facades?
2.  How to call it in my controller?

I tried following this tutorial https://github.com/setkyar/laravel-messenger-bot-management using Laravel 5.2 but couldn't make ti work.

**Comment by wittfabian** [comment]
Laravel should work out of box.

**Comment by seatechdev** [comment]
@wittfabian - Do you know what what paths I need to use in the Provides and Facades in my Laravel conifg?  I get an infinite loop with the very first bot reply with the implementation above.

**Comment by wittfabian** [comment]
I do not know the system, but I'll look at it.

**Comment by a-fawzy** [comment]
@sbasi5576  I do not know if this is the case with you or not. 
You may run into infinite loop if you subscribe to fields you do not handle. In FB webhooks page your "Page Subscription Fields" should be "messages, messaging_postbacks" which will allow you to do the basic functionalities needed by the demo on laravel page. 

For example if you subscribe to something like "message_reads" when the user read your message the webhook will call your code and if your code is not handling this kind of calls it may send back a message to the user which will call the code again after being read and cause you an infinite loop.

**Comment by wittfabian** [comment]
https://github.com/pimax/fb-messenger-php-example/blob/master/index.php

You should skip several messages.
Check the link for the following lines:

```
// Skipping delivery messages
if (!empty($message['delivery'])) {                
        continue;
}
```

**Comment by wittfabian** [comment]
Solved?

**Comment by wittfabian** [comment]
No Answer. Closed!
