### ISSUE TITLE
Messenger Platform released v1.4

### ISSUE THREAD

**Issue by a-fawzy** [pimax/fb-messenger-php#62]
Greeting guys, 
is it possible to create a project on the repository so we can avoid work duplication?

according to https://developers.facebook.com/docs/messenger-platform/changelog major changes done by FB team.

thread_settings is dropped and replaced by messenger_profile and the json structure for persistent menus and greeting message has changed. 

I will be working on both of them and I hope to finish this by end of Friday or something. If someone is working to upgrade another part affected by v1.4 please leave a reply so we avoid duplication and wasted effort.

**Comment by wittfabian** [comment]
Sure, no problem. Any wishes for the title?

**Comment by a-fawzy** [comment]
"platform v1.4 upgrades" but actually anything will be good enough. 
I just will hate if one of us here write a part of code for the upgrade just to find out later someone had already done the same.

**Comment by wittfabian** [comment]
created

**Comment by wittfabian** [comment]
Added new label for messenger v1.4
