### ISSUE TITLE
how can i send message to multiple profile

### ISSUE THREAD

**Issue by manhag** [pimax/fb-messenger-php#66]
how can i send message to multiple profile ?

**Comment by wittfabian** [comment]
My current status is: One message == One recipient

**Comment by a-fawzy** [comment]
@manhag  FB does not support sending message to multiple recipients yet. If you want to do so you must do it on your own (loop on them and send messages one by one).
It seems your bot will begin the conversation with your users. Which means your bot app need to have pages_messaging_subscriptions permission.

**Comment by manhag** [comment]
@a-fawzy  no it supports  batch sending ....  
check this 
https://developers.facebook.com/docs/graph-api/making-multiple-requests?hc_location=ufi

**Comment by manhag** [comment]
@wittfabian thanks
can you help me how to do it manually  ?
https://developers.facebook.com/docs/graph-api/making-multiple-requests?hc_location=ufi

**Comment by wittfabian** [comment]
Hi, correct me if I am wrong.
Graph API and Messenger API are not the same.

**Comment by manhag** [comment]
@wittfabian 
i asked on FBDeveloper  
they said YES ...you can 
you can post to multiple recipient  using Batch method

they are the same ... i think

**Comment by wittfabian** [comment]
Can you show me the link?

**Comment by manhag** [comment]
https://www.facebook.com/groups/fbdevelopers/permalink/1334250739951770/?comment_id=1334251809951663&reply_comment_id=1334253693284808&ref=notif&notif_t=group_comment_reply&notif_id=1488576364591450

**Comment by wittfabian** [comment]
Ok, they are the same

**Comment by manhag** [comment]
can you help me to do it ? :)

**Comment by wittfabian** [comment]
The following link describes the root Nodes of the Graph API.
https://developers.facebook.com/docs/graph-api/reference
https://developers.facebook.com/docs/graph-api/reference/v2.8/message/

You can access messages, but I can not find any example for sending messages.

**Comment by wittfabian** [comment]
I will check the documentation and test the request.
But batch requests are currently not supported with this SDK.

**Comment by manhag** [comment]
Emil Hesslow (software engineer @ Facebook) commented on my post on FB developer

can you read comments please ??

**Comment by a-fawzy** [comment]
This is how it can be done using curl:

```
curl  -i \
-F 'include_headers=false' \
-F 'access_token=ACCESSTOKEN' \
-F 'batch=[
  {
    "method":"POST",
    "headers":[{"name": "Content-Type","value": "application/json"}],
    "relative_url":"me/messages?access_token=ACCESSTOKEN",
    "body": "recipient%5Bid%5D=860782960624842&message%5Btext%5D=hello%2C+world%21"
  }, 
  {
    "method":"POST",
    "headers":[{"name": "Content-Type","value": "application/json"}],
    "relative_url":"me/messages?access_token=ACCESSTOKEN",
    "body": "recipient%5Bid%5D=860782960624842&message%5Btext%5D=hello%2C+world%21"
  }
]' \
https://graph.facebook.com/v2.8
```

you may get the body string using this:

```
$test = [
    'recipient' => [
        'id' => '860782960624842',
    ],
    'message' => [
        'text' => 'hello, world!'
    ]
];
var_dump(http_build_query($test, null, '&'));
```
Do not forget to put your own access token at the end of each relative_url

**Comment by a-fawzy** [comment]
I will need this to manage subscribers and I always thought messenger platform is separated from the graph API. So thx @manhag for bringing this to the table  :+1:

**Comment by manhag** [comment]
@a-fawzy  thanks :)
i tried your code in php  but it doesnot work 
```

$jsonData = '{
"access_token": "' .$PAGE_ACCESS_TOKEN .'",
"Facebook-API-Version":"v2.6",
batch=[
  {
    "method":"POST",
    "headers":[{"name": "Content-Type","value": "application/json"}],
    "relative_url":"me/messages?access_token=$PAGE_ACCESS_TOKEN",
    "body": "recipient%5Bid%5D=1589111404437224&message%5Btext%5D=hello%2C+world%21"
  }, 
  {
    "method":"POST",
    "headers":[{"name": "Content-Type","value": "application/json"}],
    "relative_url":"me/messages?access_token=$PAGE_ACCESS_TOKEN ",
    "body": "recipient%5Bid%5D=1197229497062040&message%5Btext%5D=hello%2C+world%21"
  }
]
}';
```

**Comment by a-fawzy** [comment]
I did not try it using php yet but it is tested and working as curl. Kindly note that request sent to the graph API is **NOT** JSON.

**Comment by manhag** [comment]
yes i know

here is the complete code
```

    /*initialize curl*/
    $ch = curl_init($url);

$jsonData = '{
"access_token": "' .$PAGE_ACCESS_TOKEN .'",
"Facebook-API-Version":"v2.6",
batch=[
  {
    "method":"POST",
    "headers":[{"name": "Content-Type","value": "application/json"}],
    "relative_url":"me/messages?access_token=$PAGE_ACCESS_TOKEN",
    "body": "recipient%5Bid%5D=1589111404437224&message%5Btext%5D=hello%2C+world%21"
  }, 
  {
    "method":"POST",
    "headers":[{"name": "Content-Type","value": "application/json"}],
    "relative_url":"me/messages?access_token=$PAGE_ACCESS_TOKEN ",
    "body": "recipient%5Bid%5D=1197229497062040&message%5Btext%5D=hello%2C+world%21"
  }
]
}';
 //   echo urlencode($JSONData1);
    
    /*curl setting to send a json post data*/ 
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonData);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));
  
        $result = curl_exec($ch); // user will get the message
    var_Dump($result); 
  
```

**Comment by a-fawzy** [comment]
This should work

```
<?php

$PAGE_ACCESS_TOKEN = '';

$ch = curl_init('https://graph.facebook.com/v2.8');

$fields['access_token'] = $PAGE_ACCESS_TOKEN;

$fields['batch'] = '
[
  {
    "method":"POST",
    "headers":[{"name": "Content-Type","value": "application/json"}],
    "relative_url":"me/messages?access_token=' . $PAGE_ACCESS_TOKEN . '",
    "body": "recipient%5Bid%5D=860782960624842&message%5Btext%5D=hello%2C+world%21"
  }, 
  {
    "method":"POST",
    "headers":[{"name": "Content-Type","value": "application/json"}],
    "relative_url":"me/messages?access_token=' . $PAGE_ACCESS_TOKEN . '",
    "body": "recipient%5Bid%5D=860782960624842&message%5Btext%5D=hello%2C+world%21"
  }
]
';

/* curl setting to send a json post data */
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $fields);

$result = curl_exec($ch);
var_dump($result);

```

**Comment by manhag** [comment]
Thanks  bro  :D 
the problem was with  BODY
can i figure out  [body] easily  more than  this method ???
like  using  JSON and convert it to php string ????
URLEncoding 

you can define headers and access_token  ONCE only 
New Code

```
$fields['access_token'] = $PAGE_ACCESS_TOKEN;
$fields['headers'] = '{"name": "Content-Type","value": "application/json"}';

$fields['batch'] = '
[
  {
    "method":"POST", 
    "relative_url":"me/messages",
    "body": "recipient%5Bid%5D=860782960624842&message%5Btext%5D=hello%2C+world%21"
  }, 
  {
    "method":"POST", 
    "relative_url":"me/messages",
    "body": "recipient%5Bid%5D=860782960624842&message%5Btext%5D=hello%2C+world%21"
  }
]
';
```
thanks ^_^ 
i wish that the method integrated with pimax package

**Comment by wittfabian** [comment]
In principle, it is the same as if you send each message individually (as "for-each-loop").
Maybe a little bit faster. I am creating a ticket for batch sending.

**Comment by erhantezakar** [comment]
This also works

> `<?php
> 
> $verify_token = ""; // Verify token
> $token = ""; // Page token
> 
> if (file_exists(__DIR__ . '/config.php')) {
>     $config = include __DIR__ . '/config.php';
>     $verify_token = $config['verify_token'];
>     $token = $config['token'];
> }
> 
> require_once(dirname(__FILE__) . '/vendor/autoload.php');
> 
> use pimax\FbBotApp;
> use pimax\Menu\MenuItem;
> use pimax\Menu\LocalizedMenu;
> use pimax\Messages\Message;
> use pimax\Messages\MessageButton;
> use pimax\Messages\StructuredMessage;
> use pimax\Messages\MessageElement;
> use pimax\Messages\MessageReceiptElement;
> use pimax\Messages\Address;
> use pimax\Messages\Summary;
> use pimax\Messages\Adjustment;
> use pimax\Messages\AccountLink;
> use pimax\Messages\ImageMessage;
> use pimax\Messages\QuickReply;
> use pimax\Messages\QuickReplyButton;
> use pimax\Messages\SenderAction;
> 
> 
> // Make Bot Instance
> $bot = new FbBotApp($token);
> 
> $bot->send(new Message(1622608101XXXXXX, 'This is a simple text message.'));
> $bot->send(new Message(1491940750YYYYYY, 'This is a simple text message.'));
> ?>
> `
