### ISSUE TITLE
how can i get user facebook id ?

### ISSUE THREAD

**Issue by manhag** [pimax/fb-messenger-php#68]
how can i get user facebook id ?

**Comment by wittfabian** [comment]
You get only the Page specific user id

**Comment by manhag** [comment]
but what about account linking ?
https://developers.facebook.com/docs/messenger-platform/messenger-profile/account-linking-url

**Comment by wittfabian** [comment]
Its the same: Check the SDK. We only use the sender id, and this id is page specific.

**Comment by manhag** [comment]
could you please check this post ?
they said  i have to use account linking to get user ID 

https://www.facebook.com/groups/fbdevelopers/permalink/1335112649865579/?comment_id=1335116233198554&ref=notif&notif_t=group_comment&notif_id=1488658989579156

**Comment by wittfabian** [comment]
My knowledge was that it is the same id. Just try it, the function is implemented.

**Comment by manhag** [comment]
thanks 
i will wait for your update :)

**Comment by manhag** [comment]
could you please give me an example  how to use account link  implemented in the project ?

**Comment by wittfabian** [comment]
Check this link:
https://developers.facebook.com/docs/messenger-platform/account-linking

> Account Linking allows you to invite users to log-in using your own authentication flow, and to receive a Messenger page-scoped ID (PSID) upon completion. You can then provide a more secure, personalized and relevant experience to users.

**Comment by manhag** [comment]
hmmm 
then i will get facebook id from user photo url 

Thanks :)

**Comment by wittfabian** [comment]
I do not think that works. You must provide a login via Facebook. The URL must point to this page (login).

**Comment by manhag** [comment]
this is my profile image  
https://l.facebook.com/l.php?u=https%3A%2F%2Fscontent.xx.fbcdn.net%2Fv%2Ft1.0-1%2F14291644_939174889527695_2227371907705202322_n.jpg 

 my facebook ID 939174889527695

**Comment by wittfabian** [comment]
For what do you want to use the id

**Comment by manhag** [comment]
i have both web Facebook application and messenger bot

so integration is needed ...to store/retrieve  data from both (web | messenger bot )

**Comment by ngethe** [comment]
there is no way to get it like 
   $FirstName = $user->getFirstName();
I need to have an id so that the bot now who it is talking to
