### ISSUE TITLE
Button POSTBACK array

### ISSUE THREAD

**Issue by sOOrf** [pimax/fb-messenger-php#7]
Require something like this
`new MessageButton(MessageButton::TYPE_POSTBACK, 'Create', ['action'=>'create', 'param1'=>'param1'] )`

**Comment by maxpinyugin** [comment]
You can use 
`new MessageButton(MessageButton::TYPE_POSTBACK, 'Create', 'create');`
Create - title
create - action

What are you mean `'param1'=>'param1'`
Postback don't support params.
