### ISSUE TITLE
how can i create my own functions ?

### ISSUE THREAD

**Issue by manhag** [pimax/fb-messenger-php#70]
i am trying to make a new function in UserProfile.php

but it show  me that message 
> Could not write “/home/........../UserProfile.php”: Permission denied

how can i do this ?

**Comment by wittfabian** [comment]
When is the error displayed?

**Comment by manhag** [comment]
![editng file](https://cloud.githubusercontent.com/assets/5571625/23586252/ff6a4cf2-0199-11e7-9642-919986b8da1b.PNG)

when i am trying to edit userprofile.php using cpanel file manager

**Comment by wittfabian** [comment]
Do you use vendor to load the package?

**Comment by wittfabian** [comment]
vendor packages are read-only by default.

**Comment by manhag** [comment]
so where i can add new functions ??

**Comment by wittfabian** [comment]
Fork the repository, implement the feature and use your own version.

OR 

Fork the repository, implement the feature, make a pull request (if the feature is good, we merge the changes)

**Comment by wittfabian** [comment]
A question on the edge: How long have you been dealing with programming, git, etc.?

**Comment by manhag** [comment]
thanks  a lot :) 
 i will try to make a pull request 

Programming......8 years 
GITHUB .. i am new  bie  ^_^ ... i know that i ask  ugly questions :(

**Comment by wittfabian** [comment]
Everyone starts small, I am glad if I can help.

**Comment by wittfabian** [comment]
The problem with your implementation in the picture is the following. The method or the functionality is not part of the official API. Maybe we can solve the issue another way around.

**Comment by manhag** [comment]
i know .. I wish to get a way to do it using official API 

I pulled a Request ... but i know it will be omitted :) 

a question on the edge ^_^ 
 i installed the master dev version  using  composer (3 days )......
 if i forked this version  
how can i replace the existing version by the new version (Forked)??

if i do editing in github...  it will update my version on my website automatically ?
or i have to do something next ???

**Comment by wittfabian** [comment]
All the stuff is done by composer.

If you want to use your own code, you must either download or publish it.
