### ISSUE TITLE
Image in a structured message

### ISSUE THREAD

**Issue by djrules24** [pimax/fb-messenger-php#76]
Hi
How do we include a image URL in a structured image ?

And the default messenger function to send an image doesn't work 
`$bot->send(new ImageMessage($message['sender']['id'], 'https://developers.facebook.com/images/devsite/fb4d_logo-2x.png'));`

**Comment by djrules24** [comment]
My existing code
`$bot->send(new StructuredMessage($message['sender']['id'],
                        StructuredMessage::TYPE_GENERIC,
                        [
                            'elements' => [
                                new MessageElement($result['title'], "", "", [
                                    new MessageButton(MessageButton::TYPE_WEB, 'Read Now', $result['permalink'])
                                				])
                            				]
                        			]
                    			));`

**Comment by wittfabian** [comment]
How do the two examples relate?
Would you like to bring the two pieces together?

**Comment by wittfabian** [comment]
No Answer. Closed!
