### ISSUE TITLE
how can i get user's location?

### ISSUE THREAD

**Issue by manhag** [pimax/fb-messenger-php#77]
this link says that i can get user location
but how can i retrieve the data ??

[https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies](https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies)

**Comment by wittfabian** [comment]
Which link?

**Comment by manhag** [comment]
sorry 
https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies

**Comment by wittfabian** [comment]
You send an Quick-Reply-Message with content_type=location.
You receive the result via Webhook:

```
{
  "object": "page",
  "entry": [
    {
      "id": "PAGE_ID",
      "time": 1472672934319,
      "messaging": [
        {
          "sender": {
            "id": "USER_ID"
          },
          "recipient": {
            "id": "PAGE_ID"
          },
          "timestamp": 1472672934259,
          "message": {
            "mid": "mid.1472672934017:db566db5104b5b5c08",
            "seq": 297,
            "attachments": [
              {
                "title": "Facebook HQ",
                "url": "https://www.facebook.com/l.php?u=https%....5-7Ocxrmg",
                "type": "location",
                "payload": {
                  "coordinates": {
                    "lat": 37.483872693672,
                    "long": -122.14900441942
                  }
                }
              }
            ]
          }
        }
      ]
    }
  ]
} 
```

**Comment by manhag** [comment]
can you show me an example please ?

**Comment by wittfabian** [comment]
This should work:

```
ret = $this->bot->send(
	new QuickReply($receiver['sender_id'], 'Send Location', 
		[
			'content_type' => 'location'
		]
));
```

**Comment by manhag** [comment]
Is this example using the project PIMAX? 
it doesnot show any buttons 
And no actions

**Comment by wittfabian** [comment]
You have to adapt the code for your case

$this->$bot describes my bot object

**Comment by wittfabian** [comment]
check pull request #79

**Comment by manhag** [comment]
thanks  
i re downloaded the last version 
and  wrote  your example in my file...but doesnot work
![image](https://cloud.githubusercontent.com/assets/5571625/24508998/75507f84-1565-11e7-9a7e-75c29eea738b.png)

**Comment by wittfabian** [comment]
```
$ret = $bot->send(new QuickReply($sender_id, 'Send Location', 
                                                   new QuickReplyButton(QuickReplyButton::TYPE_LOCATION)));
```

**Comment by wittfabian** [comment]
solved?
