### ISSUE TITLE
quick replies issue

### ISSUE THREAD

**Issue by a-fawzy** [pimax/fb-messenger-php#82]
QuickReply class the line:

```
foreach ($this->quick_replies as $qr) {
            $result['message']['quick_replies'][] = $qr->getData();
}
```
is breaking all previously created quick replies!
we used to send associative array contains the quick replies data and now you expect array of quick reply buttons.

Do you really want everyone to refactor his code when he needs to update?

**Comment by eoaddai** [comment]
same for me too. I am not able to use the dev-master branch. 
I had already submitted my bot for review. but because of this, i had to cancel the review.

**Comment by wittfabian** [comment]
The changes will be reset shortly

**Comment by wittfabian** [comment]
You should develop with one version and not constantly change the version.

**Comment by wittfabian** [comment]
Fixed

**Comment by eoaddai** [comment]
Thanks. Working perfectly now.
