### ISSUE TITLE
presistentmenu is not working. I tried the example one. it's showing nothing 

### ISSUE THREAD

**Issue by ramonov** [pimax/fb-messenger-php#84]
I tried the gitub example. other are working but persitent menu is not working. means its not being displayed. I used "set menu" where buttons are created. do i need to push it to messenger as we do for others like text etc. I can't see the files under menu folder is included on any of other files what about menuitem.php and localizedMenu.php

**Comment by wittfabian** [comment]
Maybe the example is outdated.

**Comment by ngethe** [comment]
I also had the same issue 'set menu' not working with  Undefined index: is_echo in

**Comment by a-fawzy** [comment]
The example is outdated. We were forced to do changed on how persistence menus are created because on March 2nd, 2017 Facebook changed it. 
Please follow this example:
#65

**Comment by wittfabian** [comment]
example updated
