### ISSUE TITLE
Help/Guide on list implementaion 

### ISSUE THREAD

**Issue by ngethe** [pimax/fb-messenger-php#88]
Help with Example useage on list I tried this 

               case 'g':
                    $bot->send(new StructuredMessage($message['sender']['id'],
                        StructuredMessage::TYPE_LIST,
                        [
                            'elements' => [
                                new MessageElement("top_element_style", "large", "image_url","https://www.hello.com/img_/hello_logo_hero.png" , [
                                    new MessageButton(MessageButton::TYPE_POSTBACK, 'First button'),
                                    new MessageButton(MessageButton::TYPE_WEB, 'Web link', 'http://facebook.com')
                                ]),
                                new MessageElement("Second item", "Item description", "",  "image_url","https://www.hello.com/img_/hello_logo_hero.png",  [
                                    new MessageButton(MessageButton::TYPE_POSTBACK, 'First button'),
                                    new MessageButton(MessageButton::TYPE_POSTBACK, 'Second button')
                                ]),
                                new MessageElement("Third item", "Item description", "", [
                                    new MessageButton(MessageButton::TYPE_POSTBACK, 'First button'),
                                    new MessageButton(MessageButton::TYPE_POSTBACK, 'Second button')
                                ])
                            ]
                        ]
                    ));

                break;

But NOT working

**Comment by ngethe** [comment]
Am I doing something wrong on the this implementation??

**Comment by wittfabian** [comment]
Your question has already been answered.

Check #65

**Comment by wittfabian** [comment]
And you forgot the postback urls.

**Comment by wittfabian** [comment]
use the new example
