### ISSUE TITLE
Avoid Echo looping

### ISSUE THREAD

**Issue by ngethe** [pimax/fb-messenger-php#89]
I get a number of  messages reply sent very many times
below is the code that I think should be taking care of this
but I get the error  PHP Notice:  Undefined index: message in /var/www/html/fbb/index.php on line 64   (where the below code is)
            // skip the echo of my own messages
            if (($message['message']['is_echo'] == "true")) {
                continue;
            }

**Comment by wittfabian** [comment]
Check the examples!
