### ISSUE TITLE
problem with structured message -PHP- bot messenger

### ISSUE THREAD

**Issue by cegoga** [pimax/fb-messenger-php#9]
hi!
i have a problem with my bot..
i don't know how i insert a code of a structured message in my bot PHP.

i need help to create a form for a structured message.

can you create a structured message, one of a kind, for this code?
copy, insert and past in the next comment.thanks

the rest perfect works...

this is the code:

<?php
// parameters
$hubVerifyToken = 'token';
$accessToken = "accesstoken";

// check token at setup
if ($_REQUEST['hub_verify_token'] === $hubVerifyToken) {
  echo $_REQUEST['hub_challenge'];
  exit;
}

// handle bot's anwser
$input = json_decode(file_get_contents('php://input'), true);

$senderId = $input['entry'][0]['messaging'][0]['sender']['id'];
$messageText = $input['entry'][0]['messaging'][0]['message']['text'];

if (strpos(strtolower($messageText), 'good')!== false) {
   $answer = "ok";
}

if (strpos(strtolower($messageText), 'help')!== false) {
   $answer = "yeh ";
}

}
//  structured message

?????????????

?????????????

?????????????

// end

$response = [
    'recipient' => [ 'id' => $senderId ],
    'message' => [ 'text' => $answer ]
];
$ch = curl_init('https://graph.facebook.com/v2.6/me/messages?access_token='.$accessToken);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($response));
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
curl_exec($ch);
curl_close($ch);

**Comment by maxpinyugin** [comment]
Hi
Please see this repo for examples - https://github.com/pimax/fb-messenger-php-example

Regards
