### ISSUE TITLE
Error Menu as Example

### ISSUE THREAD

**Issue by banghasan** [pimax/fb-messenger-php#90]
on https://github.com/pimax/fb-messenger-php-example/blob/master/index.php#L212

$bot->setPersistentMenu([
                        new MessageButton(MessageButton::TYPE_WEB, "First link", "http://yandex.ru"),
                        new MessageButton(MessageButton::TYPE_WEB, "Second link", "http://google.ru")
                    ]);

**ERROR:**

(
    [error] => Array
        (
            [message] => (#100) Invalid keys "type, title, url" were found in param "persistent_menu[0]".
            [type] => OAuthException
            [code] => 100
            [fbtrace_id] => GCfTzmwmTkn
        )

)

**Comment by wittfabian** [comment]
The examples is outdated. Use the example in the readme file.

**Comment by wittfabian** [comment]
And you use the wrong repo

**Comment by banghasan** [comment]
in readme

ERROR:

    [error] => Array
        (
            [message] => (#100) You must set a Get Started button if you also wish to use persistent menu.
            [type] => OAuthException
            [code] => 100
            [error_subcode] => 2018145
            [fbtrace_id] => GiNwqSd0HiH
        )

**Comment by wittfabian** [comment]
The message explain what you should do!

**Comment by banghasan** [comment]
oh okay, thx u..

**Comment by wittfabian** [comment]
"Get Started button" is implemented.
