### ISSUE TITLE
Can the pimax library be used for the bot challenge?

### ISSUE THREAD

**Issue by tag6071** [pimax/fb-messenger-php#91]
Hi, Is it ok / legal / safe to use the pimax library for the ongoing Facebook Bot Challenge?

**Comment by wittfabian** [comment]
ok: yes
legel: why not? it`s open source
safe: i don`t know. depends on your definition of "safe"

**Comment by Yiidiir** [comment]
> • Bots must comply with all Facebook for developers Messenger Platform developer guidelines and rules, and use the Messenger Platform API.
• Bots must be created on the Facebook Messenger Platform (but entrant may use any third-party tool to create or add functionality). Bots on any other platform will not be accepted.
source: https://messengerchallenge.splashthat.com/

In short, yes.

**Comment by wittfabian** [comment]
answered, closed!
