### ISSUE TITLE
How to listen to post back from quick reply button

### ISSUE THREAD

**Issue by tag6071** [pimax/fb-messenger-php#95]
Kindly make available an example to catch the POSTBACK of a quick reply button.

Thanks

**Comment by Yiidiir** [comment]
Look at this:
![Message Structure](http://dl4.joxi.net/drive/2017/04/07/0001/3503/130479/79/45f61d2616.jpg?of=1491598324613.jpg)
Clicking the QuickReply Button sends the same message structure as other types **PLUS(+)** 'quick_reply'=>'payload' under 'message'
so you can get the value of the quick reply payload with:
`
$message['message']['quick_reply']['payload'];
`
Good luck!
**EDIT:** All credit goes to @ipimax  :)

**Comment by tag6071** [comment]
Thanks Got it.
